# Generated by Django 3.0.3 on 2020-09-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
